global using SDL2;
global using SharpDune;
global using SharpDune.Audio;
global using SharpDune.Gui;
global using SharpDune.Include;
global using SharpDune.Input;
global using SharpDune.Pool;
global using SharpDune.Script;
global using SharpDune.Video;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using static CSharpDune;
global using static SharpDune.Audio.CDriver;
global using static SharpDune.Audio.Dsp;
global using static SharpDune.Audio.Midi;
global using static SharpDune.Audio.Mt32Mpu;
global using static SharpDune.Audio.Sound;
global using static SharpDune.CAnimation;
global using static SharpDune.CExplosion;
global using static SharpDune.CFile;
global using static SharpDune.CHouse;
global using static SharpDune.CObject;
global using static SharpDune.Codec.Format40;
global using static SharpDune.Codec.Format80;
global using static SharpDune.Config;
global using static SharpDune.CrashLog.CrashLog;
global using static SharpDune.CScenario;
global using static SharpDune.CString;
global using static SharpDune.CStructure;
global using static SharpDune.CTeam;
global using static SharpDune.CTile;
global using static SharpDune.CUnit;
global using static SharpDune.Cutscene;
global using static SharpDune.Gfx;
global using static SharpDune.Gui.CFont;
global using static SharpDune.Gui.CWidget;
global using static SharpDune.Gui.EditBox;
global using static SharpDune.Gui.Gui;
global using static SharpDune.Gui.Mentat;
global using static SharpDune.Gui.Security;
global using static SharpDune.Gui.Viewport;
global using static SharpDune.Gui.WidgetClick;
global using static SharpDune.Gui.WidgetDraw;
global using static SharpDune.Ini;
global using static SharpDune.IniFile;
global using static SharpDune.Input.Input;
global using static SharpDune.Input.Mouse;
global using static SharpDune.Load;
global using static SharpDune.Map;
global using static SharpDune.Os.CMath;
global using static SharpDune.Os.Common;
global using static SharpDune.Os.Endian;
global using static SharpDune.Os.Sleep;
global using static SharpDune.Pool.PoolHouse;
global using static SharpDune.Pool.PoolStructure;
global using static SharpDune.Pool.PoolTeam;
global using static SharpDune.Pool.PoolUnit;
global using static SharpDune.Save;
global using static SharpDune.SaveLoad.SaveLoad;
global using static SharpDune.SaveLoad.SaveLoadHouse;
global using static SharpDune.SaveLoad.SaveLoadInfo;
global using static SharpDune.SaveLoad.SaveLoadMap;
global using static SharpDune.SaveLoad.SaveLoadObject;
global using static SharpDune.SaveLoad.SaveLoadScenario;
global using static SharpDune.SaveLoad.SaveLoadScriptEngine;
global using static SharpDune.SaveLoad.SaveLoadStructure;
global using static SharpDune.SaveLoad.SaveLoadTeam;
global using static SharpDune.SaveLoad.SaveLoadType;
global using static SharpDune.SaveLoad.SaveLoadUnit;
global using static SharpDune.Script.General;
global using static SharpDune.Script.Script;
global using static SharpDune.Script.ScriptStructure;
global using static SharpDune.Script.ScriptTeam;
global using static SharpDune.Script.ScriptUnit;
global using static SharpDune.Sprites;
global using static SharpDune.Table.TableActionInfo;
global using static SharpDune.Table.TableAnimation;
global using static SharpDune.Table.TableExplosion;
global using static SharpDune.Table.TableHouseAnimation;
global using static SharpDune.Table.TableHouseInfo;
global using static SharpDune.Table.TableLandscapeInfo;
global using static SharpDune.Table.TableMovementType;
global using static SharpDune.Table.TableSelectionType;
global using static SharpDune.Table.TableSound;
global using static SharpDune.Table.TableStrings;
global using static SharpDune.Table.TableStructureInfo;
global using static SharpDune.Table.TableTeamAction;
global using static SharpDune.Table.TableTileDiff;
global using static SharpDune.Table.TableUnitInfo;
global using static SharpDune.Table.TableWidget;
global using static SharpDune.Table.TableWidgetInfo;
global using static SharpDune.Table.TableWindowDesc;
global using static SharpDune.Timer;
global using static SharpDune.Tools;
global using static SharpDune.Video.VideoFps;
global using static SharpDune.Video.VideoSdl2;
global using static SharpDune.Wsa;
