global using SDL2;
global using SharpDune;
global using SharpDune.Audio;
global using SharpDune.Codec;
global using SharpDune.CrashLog;
global using SharpDune.Gui;
global using SharpDune.Include;
global using SharpDune.Input;
global using SharpDune.Os;
global using SharpDune.Pool;
global using SharpDune.SaveLoad;
global using SharpDune.Script;
global using SharpDune.Video;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using static CSharpDune;
global using static SharpDune.CHouse;
global using static SharpDune.CStructure;
global using static SharpDune.CUnit;
global using static SharpDune.SaveLoad.SaveLoad;
global using static SharpDune.Script.General;
global using static SharpDune.Script.Script;
global using static SharpDune.Script.ScriptStructure;
global using static SharpDune.Script.ScriptTeam;
global using static SharpDune.Script.ScriptUnit;
global using static SharpDune.Table.TableActionInfo;
global using static SharpDune.Table.TableAnimation;
global using static SharpDune.Table.TableExplosion;
global using static SharpDune.Table.TableHouseAnimation;
global using static SharpDune.Table.TableHouseInfo;
global using static SharpDune.Table.TableLandscapeInfo;
global using static SharpDune.Table.TableMovementType;
global using static SharpDune.Table.TableSelectionType;
global using static SharpDune.Table.TableSound;
global using static SharpDune.Table.TableStrings;
global using static SharpDune.Table.TableStructureInfo;
global using static SharpDune.Table.TableTeamAction;
global using static SharpDune.Table.TableTileDiff;
global using static SharpDune.Table.TableUnitInfo;
global using static SharpDune.Table.TableWidget;
global using static SharpDune.Table.TableWidgetInfo;
global using static SharpDune.Table.TableWindowDesc;
global using static System.Math;
