global using SharpDune.Audio;
global using SharpDune.Gui;
global using SharpDune.Include;
global using SharpDune.Input;
global using SharpDune.Pool;
global using SharpDune.Script;
global using SharpDune.Video;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using static SDL2.SDL;
global using static SDL2.SDL_image;
global using static SharpDune.Animation;
global using static SharpDune.Audio.Driver;
global using static SharpDune.Audio.Dsp;
global using static SharpDune.Audio.Midi;
global using static SharpDune.Audio.Mt32Mpu;
global using static SharpDune.Audio.Sound;
global using static SharpDune.Codec.Format40;
global using static SharpDune.Codec.Format80;
global using static SharpDune.Config;
global using static SharpDune.CrashLog.CrashLog;
global using static SharpDune.Cutscene;
global using static SharpDune.Explosion;
global using static SharpDune.File;
global using static SharpDune.Gfx;
global using static SharpDune.Gui.EditBox;
global using static SharpDune.Gui.Font;
global using static SharpDune.Gui.Gui;
global using static SharpDune.Gui.Mentat;
global using static SharpDune.Gui.Security;
global using static SharpDune.Gui.Viewport;
global using static SharpDune.Gui.Widget;
global using static SharpDune.Gui.WidgetClick;
global using static SharpDune.Gui.WidgetDraw;
global using static SharpDune.House;
global using static SharpDune.Ini;
global using static SharpDune.IniFile;
global using static SharpDune.Input.Input;
global using static SharpDune.Input.Mouse;
global using static SharpDune.Load;
global using static SharpDune.Map;
global using static SharpDune.Object;
global using static SharpDune.Os.Common;
global using static SharpDune.Os.Endian;
global using static SharpDune.Os.Math;
global using static SharpDune.Os.Sleep;
global using static SharpDune.Pool.PoolHouse;
global using static SharpDune.Pool.PoolStructure;
global using static SharpDune.Pool.PoolTeam;
global using static SharpDune.Pool.PoolUnit;
global using static SharpDune.Save;
global using static SharpDune.SaveLoad.SaveLoad;
global using static SharpDune.SaveLoad.SaveLoadHouse;
global using static SharpDune.SaveLoad.SaveLoadInfo;
global using static SharpDune.SaveLoad.SaveLoadMap;
global using static SharpDune.SaveLoad.SaveLoadObject;
global using static SharpDune.SaveLoad.SaveLoadScenario;
global using static SharpDune.SaveLoad.SaveLoadScriptEngine;
global using static SharpDune.SaveLoad.SaveLoadStructure;
global using static SharpDune.SaveLoad.SaveLoadTeam;
global using static SharpDune.SaveLoad.SaveLoadType;
global using static SharpDune.SaveLoad.SaveLoadUnit;
global using static SharpDune.Scenario;
global using static SharpDune.Script.General;
global using static SharpDune.Script.Script;
global using static SharpDune.Script.ScriptStructure;
global using static SharpDune.Script.ScriptTeam;
global using static SharpDune.Script.ScriptUnit;
global using static SharpDune.SharpDune;
global using static SharpDune.Sprites;
global using static SharpDune.String;
global using static SharpDune.Structure;
global using static SharpDune.Table.TableActionInfo;
global using static SharpDune.Table.TableAnimation;
global using static SharpDune.Table.TableExplosion;
global using static SharpDune.Table.TableHouseAnimation;
global using static SharpDune.Table.TableHouseInfo;
global using static SharpDune.Table.TableLandscapeInfo;
global using static SharpDune.Table.TableMovementType;
global using static SharpDune.Table.TableSelectionType;
global using static SharpDune.Table.TableSound;
global using static SharpDune.Table.TableStrings;
global using static SharpDune.Table.TableStructureInfo;
global using static SharpDune.Table.TableTeamAction;
global using static SharpDune.Table.TableTileDiff;
global using static SharpDune.Table.TableUnitInfo;
global using static SharpDune.Table.TableWidget;
global using static SharpDune.Table.TableWidgetInfo;
global using static SharpDune.Table.TableWindowDesc;
global using static SharpDune.Team;
global using static SharpDune.Tile;
global using static SharpDune.Timer;
global using static SharpDune.Tools;
global using static SharpDune.Unit;
global using static SharpDune.Video.VideoFps;
global using static SharpDune.Video.VideoSdl2;
global using static SharpDune.Wsa;
