/* StructureInfo file table */

namespace SharpDune.Table
{
    class TableStructureInfo
    {
        internal static StructureInfo[] g_table_structureInfo;

        static TableStructureInfo()
        {
            unchecked
            {
                g_table_structureInfo = new StructureInfo[] { //[STRUCTURE_MAX]
                    new() { /* 0 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_CONCRETE,
                            name = "Concrete",
                            stringID_full = (ushort)Text.STR_SMALL_CONCRETE_SLAB,
                            wsa = "slab.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = true,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 0,
                            hitpoints = 20,
                            fogUncoverRadius = 1,
                            spriteID = 65,
                            buildCredits = 5,
                            buildTime = 16,
                            availableCampaign = 1,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_NONE,
                            sortPriority = 2,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_CONCRETE_USE_CONCRETE_TO_MAKE_A_STURDY_FOUNDATION_FOR_YOUR_STRUCTURES,
                            priorityBuild = 0,
                            priorityTarget = 5,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 0,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_1x1,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_CONCRETE_SLAB,
                        animationIndex = new byte[] {
                            2,
                            2,
                            2
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 1 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_CONCRETE_4,
                            name = "Concrete4",
                            stringID_full = (ushort)Text.STR_LARGE_CONCRETE_SLAB,
                            wsa = "4slab.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = true,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 0,
                            hitpoints = 20,
                            fogUncoverRadius = 1,
                            spriteID = 83,
                            buildCredits = 20,
                            buildTime = 16,
                            availableCampaign = 4,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_NONE,
                            sortPriority = 4,
                            upgradeLevelRequired = 1,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_CONCRETE_USE_CONCRETE_TO_MAKE_A_STURDY_FOUNDATION_FOR_YOUR_STRUCTURES,
                            priorityBuild = 0,
                            priorityTarget = 10,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 0,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_CONCRETE_SLAB,
                        animationIndex = new byte[] {
                            2,
                            2,
                            2
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 2 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_PALACE,
                            name = "Palace",
                            stringID_full = (ushort)Text.STR_HOUSE_PALACE,
                            wsa = "palace.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 1000,
                            fogUncoverRadius = 5,
                            spriteID = 66,
                            buildCredits = 999,
                            buildTime = 130,
                            availableCampaign = 8,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_STARPORT,
                            sortPriority = 5,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_PALACE_THIS_IS_YOUR_PALACE,
                            priorityBuild = 0,
                            priorityTarget = 400,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 80,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x3,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_HOUSE_PALACE,
                        animationIndex = new byte[] {
                            4,
                            4,
                            4
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 3 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_LIGHT_FCTRY,
                            name = "Light Fctry",
                            stringID_full = (ushort)Text.STR_LIGHT_VEHICLE_FACTORY,
                            wsa = "liteftry.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 350,
                            fogUncoverRadius = 3,
                            spriteID = 67,
                            buildCredits = 400,
                            buildTime = 96,
                            availableCampaign = 3,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_REFINERY | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 14,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_LIGHT_FACTORY_THE_LIGHT_FACTORY_PRODUCES_LIGHT_ATTACK_VEHICLES,
                            priorityBuild = 0,
                            priorityTarget = 200,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 20,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_LIGHT_VEHICLE_FACTORY,
                        animationIndex = new byte[] {
                            14,
                            15,
                            16
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_TRIKE,
                            (byte)UnitType.UNIT_QUAD,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            3,
                            0,
                            0,
                        },
                    },

                    new() { /* 4 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_HEAVY_FCTRY,
                            name = "Heavy Fctry",
                            stringID_full = (ushort)Text.STR_HEAVY_VEHICLE_FACTORY,
                            wsa = "hvyftry.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 200,
                            fogUncoverRadius = 3,
                            spriteID = 68,
                            buildCredits = 600,
                            buildTime = 144,
                            availableCampaign = 4,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP | StructureFlag.FLAG_STRUCTURE_LIGHT_VEHICLE),
                            sortPriority = 28,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_HEAVY_FACTORY_THE_HEAVY_FACTORY_PRODUCES_TRACKED_VEHICLES,
                            priorityBuild = 0,
                            priorityTarget = 600,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 35,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_HEAVY_VEHICLE_FACTORY,
                        animationIndex = new byte[] {
                            11,
                            12,
                            13
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_SIEGE_TANK,
                            (byte)UnitType.UNIT_LAUNCHER,
                            (byte)UnitType.UNIT_HARVESTER,
                            (byte)UnitType.UNIT_TANK,
                            (byte)UnitType.UNIT_DEVASTATOR,
                            (byte)UnitType.UNIT_DEVIATOR,
                            (byte)UnitType.UNIT_MCV,
                            (byte)UnitType.UNIT_SONIC_TANK,
                        },
                        upgradeCampaign = new ushort[] {
                            4,
                            5,
                            6,
                        },
                    },

                    new() { /* 5 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_HITECH,
                            name = "Hi-Tech",
                            stringID_full = (ushort)Text.STR_HITECH_FACTORY,
                            wsa = "hitcftry.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 400,
                            fogUncoverRadius = 3,
                            spriteID = 69,
                            buildCredits = 500,
                            buildTime = 120,
                            availableCampaign = 5,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP | StructureFlag.FLAG_STRUCTURE_LIGHT_VEHICLE),
                            sortPriority = 30,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_HITECH_FACTORY_THE_HITECH_FACTORY_PRODUCES_FLYING_VEHICLES,
                            priorityBuild = 0,
                            priorityTarget = 200,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 35,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_HI_TECH_FACTORY,
                        animationIndex = new byte[] {
                            8,
                            9,
                            10
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_CARRYALL,
                            (byte)UnitType.UNIT_ORNITHOPTER,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            7,
                            0,
                            0,
                        },
                    },

                    new() { /* 6 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_IX,
                            name = "IX",
                            stringID_full = (ushort)Text.STR_HOUSE_OF_IX,
                            wsa = "ix.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 192,
                            hitpoints = 400,
                            fogUncoverRadius = 3,
                            spriteID = 70,
                            buildCredits = 500,
                            buildTime = 120,
                            availableCampaign = 7,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_REFINERY | StructureFlag.FLAG_STRUCTURE_STARPORT | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 34,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_HOUSE_IX_THE_IX_RESEARCH_FACILITY_ADVANCES_YOUR_HOUSES_TECHNOLOGY,
                            priorityBuild = 0,
                            priorityTarget = 100,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 40,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_IX_RESEARCH,
                        animationIndex = new byte[] {
                            20,
                            20,
                            20
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 7 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_WOR,
                            name = "WOR",
                            stringID_full = (ushort)Text.STR_WOR_TROOPER_FACILITY,
                            wsa = "wor.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 400,
                            fogUncoverRadius = 3,
                            spriteID = 71,
                            buildCredits = 400,
                            buildTime = 104,
                            availableCampaign = 5,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_BARRACKS | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 20,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_WOR_WOR_IS_USED_TO_TRAIN_YOUR_HEAVY_INFANTRY,
                            priorityBuild = 0,
                            priorityTarget = 175,
                            availableHouse = (byte)(HouseFlag.FLAG_HOUSE_MERCENARY | HouseFlag.FLAG_HOUSE_SARDAUKAR | HouseFlag.FLAG_HOUSE_FREMEN | HouseFlag.FLAG_HOUSE_ORDOS | HouseFlag.FLAG_HOUSE_HARKONNEN),
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 20,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_WOR_TROOPER_FACILITY,
                        animationIndex = new byte[] {
                            21,
                            21,
                            21
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_TROOPER,
                            (byte)UnitType.UNIT_TROOPERS,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            6,
                            0,
                            0,
                        },
                    },

                    new() { /* 8 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_CONST_YARD,
                            name = "Const Yard",
                            stringID_full = (ushort)Text.STR_CONSTRUCTION_YARD,
                            wsa = "construc.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = true,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 400,
                            fogUncoverRadius = 3,
                            spriteID = 72,
                            buildCredits = 400,
                            buildTime = 80,
                            availableCampaign = 99,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_NEVER,
                            sortPriority = 0,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_CONSTRUCTION_FACILITY_ALL_STRUCTURES_ARE_BUILT_BY_THE_CONSTRUCTION_FACILITY,
                            priorityBuild = 0,
                            priorityTarget = 300,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 0,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_CONSTRUCTION_YARD,
                        animationIndex = new byte[] {
                            22,
                            22,
                            22
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            4,
                            6,
                            0,
                        },
                    },

                    new() { /* 9 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_WINDTRAP,
                            name = "Windtrap",
                            stringID_full = (ushort)Text.STR_WINDTRAP_POWER_CENTER,
                            wsa = "windtrap.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 200,
                            fogUncoverRadius = 2,
                            spriteID = 73,
                            buildCredits = 300,
                            buildTime = 48,
                            availableCampaign = 1,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_NONE,
                            sortPriority = 6,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_WINDTRAP_THE_WINDTRAP_SUPPLIES_POWER_TO_YOUR_BASE_WITHOUT_POWER_YOUR_STRUCTURES_WILL_DECAY,
                            priorityBuild = 0,
                            priorityTarget = 300,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = -100,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_WINDTRAP_POWER,
                        animationIndex = new byte[] {
                            26,
                            26,
                            26
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 10 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_BARRACKS,
                            name = "Barracks",
                            stringID_full = (ushort)Text.STR_INFANTRY_BARRACKS,
                            wsa = "barrac.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 300,
                            fogUncoverRadius = 2,
                            spriteID = 74,
                            buildCredits = 300,
                            buildTime = 72,
                            availableCampaign = 2,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 18,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_BARRACKS_THE_BARRACKS_IS_USED_TO_TRAIN_YOUR_LIGHT_INFANTRY,
                            priorityBuild = 0,
                            priorityTarget = 100,
                            availableHouse = (byte)(HouseFlag.FLAG_HOUSE_MERCENARY | HouseFlag.FLAG_HOUSE_SARDAUKAR | HouseFlag.FLAG_HOUSE_FREMEN | HouseFlag.FLAG_HOUSE_ORDOS | HouseFlag.FLAG_HOUSE_ATREIDES),
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 10,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_INFANTRY_BARRACKS,
                        animationIndex = new byte[] {
                            28,
                            28,
                            28
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_SOLDIER,
                            (byte)UnitType.UNIT_INFANTRY,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            2,
                            0,
                            0,
                        },
                    },

                    new() { /* 11 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_STARPORT,
                            name = "Starport",
                            stringID_full = (ushort)Text.STR_STARPORT_FACILITY,
                            wsa = "starport.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = true,
                                notOnConcrete = false,
                                busyStateIsIncoming = true,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 500,
                            fogUncoverRadius = 6,
                            spriteID = 75,
                            buildCredits = 500,
                            buildTime = 120,
                            availableCampaign = 6,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_REFINERY | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 32,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_STARTPORT_THE_STARPORT_IS_USED_TO_ORDER_AND_RECEIVE_SHIPMENTS_FROM_CHOAM,
                            priorityBuild = 0,
                            priorityTarget = 250,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 50,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x3,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_STARPORT_FACILITY,
                        animationIndex = new byte[] {
                            5,
                            6,
                            7
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 12 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_REFINERY,
                            name = "Refinery",
                            stringID_full = (ushort)Text.STR_SPICE_REFINERY,
                            wsa = "refinery.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = true,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 450,
                            fogUncoverRadius = 4,
                            spriteID = 76,
                            buildCredits = 400,
                            buildTime = 80,
                            availableCampaign = 1,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_WINDTRAP,
                            sortPriority = 8,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_SPICE_REFINERY_THE_REFINERY_CONVERTS_SPICE_INTO_CREDITS,
                            priorityBuild = 0,
                            priorityTarget = 300,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_HARVESTER,
                        creditsStorage = 1005,
                        powerUsage = 30,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_SPICE_REFINERY,
                        animationIndex = new byte[] {
                            17,
                            18,
                            19
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 13 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_REPAIR2,
                            name = "Repair",
                            stringID_full = (ushort)Text.STR_REPAIR_FACILITY,
                            wsa = "repair.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 200,
                            fogUncoverRadius = 3,
                            spriteID = 77,
                            buildCredits = 700,
                            buildTime = 80,
                            availableCampaign = 5,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP | StructureFlag.FLAG_STRUCTURE_LIGHT_VEHICLE),
                            sortPriority = 24,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_REPAIR_FACILITY_THE_REPAIR_FACILITY_IS_USED_TO_REPAIR_YOUR_VEHICLES,
                            priorityBuild = 0,
                            priorityTarget = 600,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)(UnitFlag.FLAG_UNIT_HARVESTER | UnitFlag.FLAG_UNIT_QUAD | UnitFlag.FLAG_UNIT_RAIDER_TRIKE | UnitFlag.FLAG_UNIT_TRIKE | UnitFlag.FLAG_UNIT_SONIC_TANK | UnitFlag.FLAG_UNIT_DEVASTATOR | UnitFlag.FLAG_UNIT_SIEGE_TANK | UnitFlag.FLAG_UNIT_TANK | UnitFlag.FLAG_UNIT_DEVIATOR | UnitFlag.FLAG_UNIT_LAUNCHER),
                        creditsStorage = 0,
                        powerUsage = 20,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_3x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_VEHICLE_REPAIR_CENTRE,
                        animationIndex = new byte[] {
                            23,
                            24,
                            25
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 14 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_WALL,
                            name = "Wall",
                            stringID_full = (ushort)Text.STR_BASE_DEFENSE_WALL,
                            wsa = "wall.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 0,
                            hitpoints = 50,
                            fogUncoverRadius = 1,
                            spriteID = 78,
                            buildCredits = 50,
                            buildTime = 40,
                            availableCampaign = 4,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 16,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_WALL_THE_WALL_IS_USED_FOR_PASSIVE_DEFENSE,
                            priorityBuild = 0,
                            priorityTarget = 30,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 0,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_1x1,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_WALLS,
                        animationIndex = new byte[] {
                            0xFF,
                            0xFF,
                            0xFF
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 15 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_TURRET,
                            name = "Turret",
                            stringID_full = (ushort)Text.STR_CANNON_TURRET,
                            wsa = "turret.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 200,
                            fogUncoverRadius = 2,
                            spriteID = 79,
                            buildCredits = 125,
                            buildTime = 64,
                            availableCampaign = 5,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 22,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_GUN_TURRET_THE_CANNON_TURRET_IS_USED_FOR_SHORT_RANGE_ACTIVE_DEFENSE,
                            priorityBuild = 75,
                            priorityTarget = 150,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 10,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_1x1,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_BASE_DEFENSE_TURRET,
                        animationIndex = new byte[] {
                            0xFF,
                            0xFF,
                            0xFF
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 16 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_RTURRET,
                            name = "R-Turret",
                            stringID_full = (ushort)Text.STR_ROCKET_TURRET,
                            wsa = "rturret.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 64,
                            hitpoints = 200,
                            fogUncoverRadius = 5,
                            spriteID = 80,
                            buildCredits = 250,
                            buildTime = 96,
                            availableCampaign = 0,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_OUTPOST | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 26,
                            upgradeLevelRequired = 2,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_ROCKET_TURRET_THE_ROCKETCANNON_TURRET_IS_USED_FOR_BOTH_SHORT_AND_MEDIUM_RANGE_ACTIVE_DEFENSE,
                            priorityBuild = 100,
                            priorityTarget = 75,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 25,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_1x1,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_BASE_ROCKET_TURRET,
                        animationIndex = new byte[] {
                            0xFF,
                            0xFF,
                            0xFF
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 17 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_SPICE_SILO,
                            name = "Spice Silo",
                            stringID_full = (ushort)Text.STR_SPICE_STORAGE_SILO,
                            wsa = "storage.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = true,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 0,
                            hitpoints = 150,
                            fogUncoverRadius = 2,
                            spriteID = 81,
                            buildCredits = 150,
                            buildTime = 48,
                            availableCampaign = 2,
                            structuresRequired = (uint)(StructureFlag.FLAG_STRUCTURE_REFINERY | StructureFlag.FLAG_STRUCTURE_WINDTRAP),
                            sortPriority = 12,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_SPICE_SILO_THE_SPICE_SILO_IS_USED_TO_STORE_REFINED_SPICE,
                            priorityBuild = 0,
                            priorityTarget = 150,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 1000,
                        powerUsage = 5,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_SPICE_STORAGE_SILO,
                        animationIndex = new byte[] {
                            27,
                            27,
                            27
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    },

                    new() { /* 18 */
		                o = new ObjectInfo {
                            stringID_abbrev = (ushort)Text.STR_OUTPOST,
                            name = "Outpost",
                            stringID_full = (ushort)Text.STR_RADAR_OUTPOST,
                            wsa = "headqrts.wsa",
                            flags = new ObjectInfoFlags {
                                hasShadow = false,
                                factory = false,
                                notOnConcrete = false,
                                busyStateIsIncoming = false,
                                blurTile = false,
                                hasTurret = false,
                                conquerable = false,
                                canBePickedUp = false,
                                noMessageOnDeath = false,
                                tabSelectable = false,
                                scriptNoSlowdown = false,
                                targetAir = false,
                                priority = false
                            },
                            spawnChance = 128,
                            hitpoints = 500,
                            fogUncoverRadius = 10,
                            spriteID = 82,
                            buildCredits = 400,
                            buildTime = 80,
                            availableCampaign = 2,
                            structuresRequired = (uint)StructureFlag.FLAG_STRUCTURE_WINDTRAP,
                            sortPriority = 10,
                            upgradeLevelRequired = 0,
                            actionsPlayer = new[] { (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK, (ushort)ActionType.ACTION_ATTACK },
                            available = 0,
                            hintStringID = (ushort)Text.STR_OUTPOST_THE_OUTPOST_PROVIDES_RADAR_AND_AIDS_CONTROL_OF_DISTANT_VEHICLES,
                            priorityBuild = 0,
                            priorityTarget = 275,
                            availableHouse = (byte)HouseFlag.FLAG_HOUSE_ALL,
                        },
                        enterFilter = (uint)UnitFlag.FLAG_UNIT_NONE,
                        creditsStorage = 0,
                        powerUsage = 30,
                        layout = (ushort)StructureLayout.STRUCTURE_LAYOUT_2x2,
                        iconGroup = (ushort)IconMapEntries.ICM_ICONGROUP_RADAR_OUTPOST,
                        animationIndex = new byte[] {
                            3,
                            3,
                            3
                        },
                        buildableUnits = new[] {
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                            (byte)UnitType.UNIT_INVALID,
                        },
                        upgradeCampaign = new ushort[] {
                            0,
                            0,
                            0,
                        },
                    }
                };
            }
        }

        /* Array with position offset per tile in a structure layout. */
        internal static ushort[][] g_table_structure_layoutTiles = { //[STRUCTURE_LAYOUT_MAX][9]
	        new ushort[] {0,    0,    0,    0,     0,     0,     0,     0,     0}, /* STRUCTURE_LAYOUT_1x1 */
	        new ushort[] {0,    1,    0,    0,     0,     0,     0,     0,     0}, /* STRUCTURE_LAYOUT_2x1 */
	        new ushort[] {0, 64+0,    0,    0,     0,     0,     0,     0,     0}, /* STRUCTURE_LAYOUT_1x2 */
	        new ushort[] {0,    1, 64+0, 64+1,     0,     0,     0,     0,     0}, /* STRUCTURE_LAYOUT_2x2 */
	        new ushort[] {0,    1, 64+0, 64+1, 128+0, 128+1,     0,     0,     0}, /* STRUCTURE_LAYOUT_2x3 */
	        new ushort[] {0,    1,    2, 64+0,  64+1,  64+2,     0,     0,     0}, /* STRUCTURE_LAYOUT_3x2 */
	        new ushort[] {0,    1,    2, 64+0,  64+1,  64+2, 128+0, 128+1, 128+2}  /* STRUCTURE_LAYOUT_3x3 */
        };

        /* Array with position offset of edge tiles in a structure layout. */
        internal static ushort[][] g_table_structure_layoutEdgeTiles = { //[STRUCTURE_LAYOUT_MAX][8]
	        new ushort[] {0, 0,    0,     0,     0,     0,     0, 0}, /* STRUCTURE_LAYOUT_1x1 */
	        new ushort[] {0, 1,    1,     1,     1,     0,     0, 0}, /* STRUCTURE_LAYOUT_2x1 */
	        new ushort[] {0, 0,    0,  64+0,  64+0,  64+0,     0, 0}, /* STRUCTURE_LAYOUT_1x2 */
	        new ushort[] {0, 1,    1,  64+1,  64+1,  64+0,  64+0, 0}, /* STRUCTURE_LAYOUT_2x2 */
	        new ushort[] {0, 1, 64+1, 128+1, 128+1, 128+0,  64+0, 0}, /* STRUCTURE_LAYOUT_2x3 */
	        new ushort[] {1, 2,    2,  64+2,  64+1,  64+0,     0, 0}, /* STRUCTURE_LAYOUT_3x2 */
	        new ushort[] {1, 2, 64+2, 128+2, 128+1, 128+0,  64+0, 0}, /* STRUCTURE_LAYOUT_3x3 */
        };

        /* Array with number of tiles in a layout. */
        internal static ushort[] g_table_structure_layoutTileCount = { //[STRUCTURE_LAYOUT_MAX]
            1, /* STRUCTURE_LAYOUT_1x1 */
	        2, /* STRUCTURE_LAYOUT_2x1 */
	        2, /* STRUCTURE_LAYOUT_1x2 */
	        4, /* STRUCTURE_LAYOUT_2x2 */
	        6, /* STRUCTURE_LAYOUT_2x3 */
	        6, /* STRUCTURE_LAYOUT_3x2 */
	        9, /* STRUCTURE_LAYOUT_3x3 */
        };

        /* Array with TileDiff of a layout. */
        internal static tile32[] g_table_structure_layoutTileDiff = { //[STRUCTURE_LAYOUT_MAX]
            new() { x = 0x0080, y = 0x0080 }, /* STRUCTURE_LAYOUT_1x1 */
	        new() { x = 0x0100, y = 0x0080 }, /* STRUCTURE_LAYOUT_2x1 */
	        new() { x = 0x0080, y = 0x0100 }, /* STRUCTURE_LAYOUT_1x2 */
	        new() { x = 0x0100, y = 0x0100 }, /* STRUCTURE_LAYOUT_2x2 */
	        new() { x = 0x0100, y = 0x0180 }, /* STRUCTURE_LAYOUT_2x3 */
	        new() { x = 0x0280, y = 0x0100 }, /* STRUCTURE_LAYOUT_3x2 */
	        new() { x = 0x0180, y = 0x0180 }, /* STRUCTURE_LAYOUT_3x3 */
        };

        /* Array with size of a layout. */
        internal static XYSize[] g_table_structure_layoutSize = { //[STRUCTURE_LAYOUT_MAX]
            new() { width = 1, height = 1 }, /* STRUCTURE_LAYOUT_1x1 */
	        new() { width = 2, height = 1 }, /* STRUCTURE_LAYOUT_2x1 */
	        new() { width = 1, height = 2 }, /* STRUCTURE_LAYOUT_1x2 */
	        new() { width = 2, height = 2 }, /* STRUCTURE_LAYOUT_2x2 */
	        new() { width = 2, height = 3 }, /* STRUCTURE_LAYOUT_2x3 */
	        new() { width = 3, height = 2 }, /* STRUCTURE_LAYOUT_3x2 */
	        new() { width = 3, height = 3 }, /* STRUCTURE_LAYOUT_3x3 */
        };

        /* Array with position offset per tile around a structure layout. */
        internal static readonly short[][] g_table_structure_layoutTilesAround = { //[STRUCTURE_LAYOUT_MAX][16]
	        new short[] {-64, -64+1,     1,  64+1,  64+0,  64-1,    -1, -64-1,     0,     0,     0,     0,     0,     0,  0,     0}, /* STRUCTURE_LAYOUT_1x1 */
	        new short[] {-64, -64+1, -64+2,     2,  64+2,  64+1,  64+0,  64-1,    -1, -64-1,     0,     0,     0,     0,  0,     0}, /* STRUCTURE_LAYOUT_2x1 */
	        new short[] {-64, -64+1,     1,  64+1, 128+1, 128+0, 128-1,  64-1,    -1, -64-1,     0,     0,     0,     0,  0,     0}, /* STRUCTURE_LAYOUT_1x2 */
	        new short[] {-64, -64+1, -64+2,     2,  64+2, 128+2, 128+1, 128+0, 128-1,  64-1,    -1, -64-1,     0,     0,  0,     0}, /* STRUCTURE_LAYOUT_2x2 */
	        new short[] {-64, -64+1, -64+2,     2,  64+2, 128+2, 192+2, 192+1, 192+0, 192-1, 128-1,  64-1,    -1, -64-1,  0,     0}, /* STRUCTURE_LAYOUT_2x3 */
	        new short[] {-64, -64+1, -64+2, -64+3,     3,  64+3, 128+3, 128+2, 128+1, 128+0, 128-1,  64-1,    -1, -64-1,  0,     0}, /* STRUCTURE_LAYOUT_3x2 */
	        new short[] {-64, -64+1, -64+2, -64+3,     3,  64+3, 128+3, 192+3, 192+2, 192+1, 192+0, 192-1, 128-1,  64-1, -1, -64-1}, /* STRUCTURE_LAYOUT_3x3 */
        };
    }
}
